@Hng12Stage1_HostAddress = http://localhost:5073

GET {{Hng12Stage1_HostAddress}}/api/classify-number?number=34rt
Accept: application/json

###
GET {{Hng12Stage1_HostAddress}}/api/classify-number?number=371
Accept: application/json

###
GET {{Hng12Stage1_HostAddress}}/api/classify-number?number=11
Accept: application/json